/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 12.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Category {
    'categoryCode'?: string;
    'tradeDivision'?: string;
    'tradeGroup'?: string;
    'subClass'?: string;
    '_class'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "categoryCode",
            "baseName": "categoryCode",
            "type": "string"
        },
        {
            "name": "tradeDivision",
            "baseName": "tradeDivision",
            "type": "string"
        },
        {
            "name": "tradeGroup",
            "baseName": "tradeGroup",
            "type": "string"
        },
        {
            "name": "subClass",
            "baseName": "subClass",
            "type": "string"
        },
        {
            "name": "_class",
            "baseName": "class",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Category.attributeTypeMap;
    }
}

