/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Cbsa } from './cbsa';
import { Mcd } from './mcd';

export class Census {
    'cbsa'?: Cbsa;
    'matchLevel'?: string;
    'matchCode'?: string;
    'tract'?: string;
    'mcd'?: Mcd;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cbsa",
            "baseName": "cbsa",
            "type": "Cbsa"
        },
        {
            "name": "matchLevel",
            "baseName": "matchLevel",
            "type": "string"
        },
        {
            "name": "matchCode",
            "baseName": "matchCode",
            "type": "string"
        },
        {
            "name": "tract",
            "baseName": "tract",
            "type": "string"
        },
        {
            "name": "mcd",
            "baseName": "mcd",
            "type": "Mcd"
        }    ];

    static getAttributeTypeMap() {
        return Census.attributeTypeMap;
    }
}

