/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CrimeRiskPreferences } from './crimeRiskPreferences';
import { RiskAddress } from './riskAddress';

export class CrimeRiskByAddressBatchRequest {
    'addresses': Array<RiskAddress>;
    'preferences'?: CrimeRiskPreferences;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "addresses",
            "baseName": "addresses",
            "type": "Array<RiskAddress>"
        },
        {
            "name": "preferences",
            "baseName": "preferences",
            "type": "CrimeRiskPreferences"
        }    ];

    static getAttributeTypeMap() {
        return CrimeRiskByAddressBatchRequest.attributeTypeMap;
    }
}

