/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DemographicsAdvancedPreferences } from './demographicsAdvancedPreferences';
import { DemographicsGeometry } from './demographicsGeometry';

export class DemographicsAdvancedRequest {
    'preferences'?: DemographicsAdvancedPreferences;
    'geometry'?: DemographicsGeometry;
    'geometryAsText'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "preferences",
            "baseName": "preferences",
            "type": "DemographicsAdvancedPreferences"
        },
        {
            "name": "geometry",
            "baseName": "geometry",
            "type": "DemographicsGeometry"
        },
        {
            "name": "geometryAsText",
            "baseName": "geometryAsText",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DemographicsAdvancedRequest.attributeTypeMap;
    }
}

