/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AssetsAndWealthTheme } from './assetsAndWealthTheme';
import { EducationTheme } from './educationTheme';
import { EmploymentTheme } from './employmentTheme';
import { ExpenditureTheme } from './expenditureTheme';
import { HealthTheme } from './healthTheme';
import { HouseholdsTheme } from './householdsTheme';
import { HousingTheme } from './housingTheme';
import { IncomeTheme } from './incomeTheme';
import { PopulationTheme } from './populationTheme';
import { RaceAndEthnicityTheme } from './raceAndEthnicityTheme';
import { SupplyAndDemandTheme } from './supplyAndDemandTheme';

export class DemographicsThemesV2 {
    'boundaryId'?: string;
    'populationTheme'?: PopulationTheme;
    'raceAndEthnicityTheme'?: RaceAndEthnicityTheme;
    'healthTheme'?: HealthTheme;
    'educationTheme'?: EducationTheme;
    'incomeTheme'?: IncomeTheme;
    'assetsAndWealthTheme'?: AssetsAndWealthTheme;
    'householdsTheme'?: HouseholdsTheme;
    'housingTheme'?: HousingTheme;
    'employmentTheme'?: EmploymentTheme;
    'expenditureTheme'?: ExpenditureTheme;
    'supplyAndDemandTheme'?: SupplyAndDemandTheme;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "boundaryId",
            "baseName": "boundaryId",
            "type": "string"
        },
        {
            "name": "populationTheme",
            "baseName": "populationTheme",
            "type": "PopulationTheme"
        },
        {
            "name": "raceAndEthnicityTheme",
            "baseName": "raceAndEthnicityTheme",
            "type": "RaceAndEthnicityTheme"
        },
        {
            "name": "healthTheme",
            "baseName": "healthTheme",
            "type": "HealthTheme"
        },
        {
            "name": "educationTheme",
            "baseName": "educationTheme",
            "type": "EducationTheme"
        },
        {
            "name": "incomeTheme",
            "baseName": "incomeTheme",
            "type": "IncomeTheme"
        },
        {
            "name": "assetsAndWealthTheme",
            "baseName": "assetsAndWealthTheme",
            "type": "AssetsAndWealthTheme"
        },
        {
            "name": "householdsTheme",
            "baseName": "householdsTheme",
            "type": "HouseholdsTheme"
        },
        {
            "name": "housingTheme",
            "baseName": "housingTheme",
            "type": "HousingTheme"
        },
        {
            "name": "employmentTheme",
            "baseName": "employmentTheme",
            "type": "EmploymentTheme"
        },
        {
            "name": "expenditureTheme",
            "baseName": "expenditureTheme",
            "type": "ExpenditureTheme"
        },
        {
            "name": "supplyAndDemandTheme",
            "baseName": "supplyAndDemandTheme",
            "type": "SupplyAndDemandTheme"
        }    ];

    static getAttributeTypeMap() {
        return DemographicsThemesV2.attributeTypeMap;
    }
}

