/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GeoLocationFixedLineCountry } from './geoLocationFixedLineCountry';

export class DeviceStatusNetwork {
    'carrier'?: string;
    'callType'?: string;
    'locAccuracySupport'?: string;
    'nationalNumber'?: string;
    'country'?: GeoLocationFixedLineCountry;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "carrier",
            "baseName": "carrier",
            "type": "string"
        },
        {
            "name": "callType",
            "baseName": "callType",
            "type": "string"
        },
        {
            "name": "locAccuracySupport",
            "baseName": "locAccuracySupport",
            "type": "string"
        },
        {
            "name": "nationalNumber",
            "baseName": "nationalNumber",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "GeoLocationFixedLineCountry"
        }    ];

    static getAttributeTypeMap() {
        return DeviceStatusNetwork.attributeTypeMap;
    }
}

