/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Depth } from './depth';
import { EarthquakeDateTime } from './earthquakeDateTime';
import { EarthquakeLocation } from './earthquakeLocation';
import { Magnitude } from './magnitude';

export class EarthquakeEvent {
    'dateTime'?: EarthquakeDateTime;
    'seismicRegionNumber'?: number;
    'depth'?: Depth;
    'magnitude'?: Magnitude;
    'cause'?: string;
    'culturalEffect'?: string;
    'intensity'?: number;
    'diastrophism'?: string;
    'miscPhenomena'?: string;
    'location'?: EarthquakeLocation;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dateTime",
            "baseName": "dateTime",
            "type": "EarthquakeDateTime"
        },
        {
            "name": "seismicRegionNumber",
            "baseName": "seismicRegionNumber",
            "type": "number"
        },
        {
            "name": "depth",
            "baseName": "depth",
            "type": "Depth"
        },
        {
            "name": "magnitude",
            "baseName": "magnitude",
            "type": "Magnitude"
        },
        {
            "name": "cause",
            "baseName": "cause",
            "type": "string"
        },
        {
            "name": "culturalEffect",
            "baseName": "culturalEffect",
            "type": "string"
        },
        {
            "name": "intensity",
            "baseName": "intensity",
            "type": "number"
        },
        {
            "name": "diastrophism",
            "baseName": "diastrophism",
            "type": "string"
        },
        {
            "name": "miscPhenomena",
            "baseName": "miscPhenomena",
            "type": "string"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "EarthquakeLocation"
        }    ];

    static getAttributeTypeMap() {
        return EarthquakeEvent.attributeTypeMap;
    }
}

