/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 12.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FireStation } from './fireStation';
import { RiskAddress } from './riskAddress';

export class FireStations {
    'fireStation'?: Array<FireStation>;
    'matchedAddress'?: RiskAddress;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fireStation",
            "baseName": "fireStation",
            "type": "Array<FireStation>"
        },
        {
            "name": "matchedAddress",
            "baseName": "matchedAddress",
            "type": "RiskAddress"
        }    ];

    static getAttributeTypeMap() {
        return FireStations.attributeTypeMap;
    }
}

