/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Distance } from './distance';
import { FireDepartment } from './fireDepartment';
import { FireStationContactDetails } from './fireStationContactDetails';
import { Geometry } from './geometry';
import { Time } from './time';

export class FireStation {
    'numWithinDepartment'?: string;
    'locationReference'?: string;
    'travelDistance'?: Distance;
    'travelTime'?: Time;
    'contactDetails'?: FireStationContactDetails;
    'fireDepartment'?: FireDepartment;
    'geometry'?: Geometry;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "numWithinDepartment",
            "baseName": "numWithinDepartment",
            "type": "string"
        },
        {
            "name": "locationReference",
            "baseName": "locationReference",
            "type": "string"
        },
        {
            "name": "travelDistance",
            "baseName": "travelDistance",
            "type": "Distance"
        },
        {
            "name": "travelTime",
            "baseName": "travelTime",
            "type": "Time"
        },
        {
            "name": "contactDetails",
            "baseName": "contactDetails",
            "type": "FireStationContactDetails"
        },
        {
            "name": "fireDepartment",
            "baseName": "fireDepartment",
            "type": "FireDepartment"
        },
        {
            "name": "geometry",
            "baseName": "geometry",
            "type": "Geometry"
        }    ];

    static getAttributeTypeMap() {
        return FireStation.attributeTypeMap;
    }
}

