/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FireEventsResponse } from './fireEventsResponse';

export class FireHistory {
    'stateCode'?: string;
    'postCode'?: string;
    'events'?: FireEventsResponse;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "stateCode",
            "baseName": "stateCode",
            "type": "string"
        },
        {
            "name": "postCode",
            "baseName": "postCode",
            "type": "string"
        },
        {
            "name": "events",
            "baseName": "events",
            "type": "FireEventsResponse"
        }    ];

    static getAttributeTypeMap() {
        return FireHistory.attributeTypeMap;
    }
}

