/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 12.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CommonGeometry } from './commonGeometry';
import { Risk } from './risk';

export class FireShed {
    'id'?: number;
    'risk'?: Risk;
    'geometry'?: CommonGeometry;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "risk",
            "baseName": "risk",
            "type": "Risk"
        },
        {
            "name": "geometry",
            "baseName": "geometry",
            "type": "CommonGeometry"
        }    ];

    static getAttributeTypeMap() {
        return FireShed.attributeTypeMap;
    }
}

