/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 12.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BaseFloodElevation } from './baseFloodElevation';
import { PrimaryZone } from './primaryZone';

export class FloodZone {
    'code'?: string;
    'areaType'?: string;
    'riskLevel'?: string;
    'primaryZone'?: PrimaryZone;
    'baseFloodElevation'?: BaseFloodElevation;
    'additionalInfo'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "areaType",
            "baseName": "areaType",
            "type": "string"
        },
        {
            "name": "riskLevel",
            "baseName": "riskLevel",
            "type": "string"
        },
        {
            "name": "primaryZone",
            "baseName": "primaryZone",
            "type": "PrimaryZone"
        },
        {
            "name": "baseFloodElevation",
            "baseName": "baseFloodElevation",
            "type": "BaseFloodElevation"
        },
        {
            "name": "additionalInfo",
            "baseName": "additionalInfo",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FloodZone.attributeTypeMap;
    }
}

