/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Community } from './community';
import { CrimeBoundary } from './crimeBoundary';
import { FloodZone } from './floodZone';
import { RiskAddress } from './riskAddress';
import { State } from './state';

export class FloodRiskResponse {
    'objectId'?: string;
    'state'?: State;
    'floodZone'?: FloodZone;
    'community'?: Community;
    'boundary'?: CrimeBoundary;
    'matchedAddress'?: RiskAddress;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "objectId",
            "baseName": "objectId",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "State"
        },
        {
            "name": "floodZone",
            "baseName": "floodZone",
            "type": "FloodZone"
        },
        {
            "name": "community",
            "baseName": "community",
            "type": "Community"
        },
        {
            "name": "boundary",
            "baseName": "boundary",
            "type": "CrimeBoundary"
        },
        {
            "name": "matchedAddress",
            "baseName": "matchedAddress",
            "type": "RiskAddress"
        }    ];

    static getAttributeTypeMap() {
        return FloodRiskResponse.attributeTypeMap;
    }
}

