/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FreeOrReducedPriceLunches {
    'freeLunchesCount'?: string;
    'reducedPriceLunchedCount'?: string;
    'totalCount'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "freeLunchesCount",
            "baseName": "freeLunchesCount",
            "type": "string"
        },
        {
            "name": "reducedPriceLunchedCount",
            "baseName": "reducedPriceLunchedCount",
            "type": "string"
        },
        {
            "name": "totalCount",
            "baseName": "totalCount",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FreeOrReducedPriceLunches.attributeTypeMap;
    }
}

