/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GeocodeAddress } from './geocodeAddress';
import { GeocodePreferences } from './geocodePreferences';

export class GeocodeRequest {
    'type'?: string;
    'preferences'?: GeocodePreferences;
    'addresses': Array<GeocodeAddress>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "preferences",
            "baseName": "preferences",
            "type": "GeocodePreferences"
        },
        {
            "name": "addresses",
            "baseName": "addresses",
            "type": "Array<GeocodeAddress>"
        }    ];

    static getAttributeTypeMap() {
        return GeocodeRequest.attributeTypeMap;
    }
}

