/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetPostalCodesAPIInput } from './getPostalCodesAPIInput';
import { GetPostalCodesAPIOptions } from './getPostalCodesAPIOptions';

export class GetPostalCodesAPIRequest {
    'options'?: GetPostalCodesAPIOptions;
    'input'?: GetPostalCodesAPIInput;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "options",
            "baseName": "options",
            "type": "GetPostalCodesAPIOptions"
        },
        {
            "name": "input",
            "baseName": "Input",
            "type": "GetPostalCodesAPIInput"
        }    ];

    static getAttributeTypeMap() {
        return GetPostalCodesAPIRequest.attributeTypeMap;
    }
}

