/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GeoLocationPlace } from './geoLocationPlace';
import { Network } from './network';
import { Proxy } from './proxy';

export class IpInfo {
    'ipAddress'?: string;
    'proxy'?: Proxy;
    'network'?: Network;
    'place'?: GeoLocationPlace;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ipAddress",
            "baseName": "ipAddress",
            "type": "string"
        },
        {
            "name": "proxy",
            "baseName": "proxy",
            "type": "Proxy"
        },
        {
            "name": "network",
            "baseName": "network",
            "type": "Network"
        },
        {
            "name": "place",
            "baseName": "place",
            "type": "GeoLocationPlace"
        }    ];

    static getAttributeTypeMap() {
        return IpInfo.attributeTypeMap;
    }
}

