/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Magnitude {
    'value'?: number;
    'scale'?: string;
    'bodyWave'?: number;
    'surfaceWave'?: number;
    'surfaceWaveValue'?: number;
    'bodyWaveValue'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "number"
        },
        {
            "name": "scale",
            "baseName": "scale",
            "type": "string"
        },
        {
            "name": "bodyWave",
            "baseName": "bodyWave",
            "type": "number"
        },
        {
            "name": "surfaceWave",
            "baseName": "surfaceWave",
            "type": "number"
        },
        {
            "name": "surfaceWaveValue",
            "baseName": "surfaceWaveValue",
            "type": "number"
        },
        {
            "name": "bodyWaveValue",
            "baseName": "bodyWaveValue",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Magnitude.attributeTypeMap;
    }
}

