/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 12.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Carrier } from './carrier';
import { OrganizationType } from './organizationType';

export class Network {
    'connectionFromHome'?: string;
    'organization'?: string;
    'carrier'?: Carrier;
    'organizationType'?: OrganizationType;
    'connectionType'?: string;
    'lineSpeed'?: string;
    'ipRouteType'?: string;
    'hostingFacility'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "connectionFromHome",
            "baseName": "connectionFromHome",
            "type": "string"
        },
        {
            "name": "organization",
            "baseName": "organization",
            "type": "string"
        },
        {
            "name": "carrier",
            "baseName": "carrier",
            "type": "Carrier"
        },
        {
            "name": "organizationType",
            "baseName": "organizationType",
            "type": "OrganizationType"
        },
        {
            "name": "connectionType",
            "baseName": "connectionType",
            "type": "string"
        },
        {
            "name": "lineSpeed",
            "baseName": "lineSpeed",
            "type": "string"
        },
        {
            "name": "ipRouteType",
            "baseName": "ipRouteType",
            "type": "string"
        },
        {
            "name": "hostingFacility",
            "baseName": "hostingFacility",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Network.attributeTypeMap;
    }
}

