/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Center } from './center';
import { MatchedAddress } from './matchedAddress';
import { Parcel } from './parcel';
import { PropertyInformationGeometry } from './propertyInformationGeometry';

export class ParcelBoundary {
    'objectId'?: string;
    'apn'?: string;
    'pid'?: string;
    'center'?: Center;
    'countyfips'?: string;
    'geometry'?: PropertyInformationGeometry;
    'parcelList'?: Array<Parcel>;
    'adjacentParcelBoundary'?: Array<ParcelBoundary>;
    'matchedAddress'?: MatchedAddress;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "objectId",
            "baseName": "objectId",
            "type": "string"
        },
        {
            "name": "apn",
            "baseName": "apn",
            "type": "string"
        },
        {
            "name": "pid",
            "baseName": "pid",
            "type": "string"
        },
        {
            "name": "center",
            "baseName": "center",
            "type": "Center"
        },
        {
            "name": "countyfips",
            "baseName": "countyfips",
            "type": "string"
        },
        {
            "name": "geometry",
            "baseName": "geometry",
            "type": "PropertyInformationGeometry"
        },
        {
            "name": "parcelList",
            "baseName": "parcelList",
            "type": "Array<Parcel>"
        },
        {
            "name": "adjacentParcelBoundary",
            "baseName": "adjacentParcelBoundary",
            "type": "Array<ParcelBoundary>"
        },
        {
            "name": "matchedAddress",
            "baseName": "matchedAddress",
            "type": "MatchedAddress"
        }    ];

    static getAttributeTypeMap() {
        return ParcelBoundary.attributeTypeMap;
    }
}

