/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Pbkey } from './pbkey';

export class PBKeyResponseList {
    'pbkey'?: Array<Pbkey>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "pbkey",
            "baseName": "pbkey",
            "type": "Array<Pbkey>"
        }    ];

    static getAttributeTypeMap() {
        return PBKeyResponseList.attributeTypeMap;
    }
}

