/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Center } from './center';
import { ZonesAddress } from './zonesAddress';
import { ZonesPoi } from './zonesPoi';
import { ZonesPoiGeometry } from './zonesPoiGeometry';

export class PoiBoundary {
    'objectId'?: string;
    'center'?: Center;
    'countyfips'?: string;
    'geometry'?: ZonesPoiGeometry;
    'poiList'?: Array<ZonesPoi>;
    'matchedAddress'?: ZonesAddress;
    'id'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "objectId",
            "baseName": "objectId",
            "type": "string"
        },
        {
            "name": "center",
            "baseName": "center",
            "type": "Center"
        },
        {
            "name": "countyfips",
            "baseName": "countyfips",
            "type": "string"
        },
        {
            "name": "geometry",
            "baseName": "geometry",
            "type": "ZonesPoiGeometry"
        },
        {
            "name": "poiList",
            "baseName": "poiList",
            "type": "Array<ZonesPoi>"
        },
        {
            "name": "matchedAddress",
            "baseName": "matchedAddress",
            "type": "ZonesAddress"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PoiBoundary.attributeTypeMap;
    }
}

