/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 12.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RouteGeometry } from './routeGeometry';

export class RouteDirection {
    'distance'?: number;
    'distanceUnit'?: string;
    'timeUnit'?: string;
    'time'?: number;
    'instruction'?: string;
    'directionGeometry'?: RouteGeometry;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "distance",
            "baseName": "distance",
            "type": "number"
        },
        {
            "name": "distanceUnit",
            "baseName": "distanceUnit",
            "type": "string"
        },
        {
            "name": "timeUnit",
            "baseName": "timeUnit",
            "type": "string"
        },
        {
            "name": "time",
            "baseName": "time",
            "type": "number"
        },
        {
            "name": "instruction",
            "baseName": "instruction",
            "type": "string"
        },
        {
            "name": "directionGeometry",
            "baseName": "directionGeometry",
            "type": "RouteGeometry"
        }    ];

    static getAttributeTypeMap() {
        return RouteDirection.attributeTypeMap;
    }
}

