/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FreeOrReducedPriceLunches } from './freeOrReducedPriceLunches';
import { StudentEthnicity } from './studentEthnicity';

export class SchoolProfile {
    'blueRibbon'?: string;
    'internationalBaccalaureate'?: string;
    'titleI'?: string;
    'expensePerStudent'?: string;
    'studentBelowPovertyPct'?: string;
    'advancePlacementClasses'?: string;
    'freeOrReducedPriceLunches'?: FreeOrReducedPriceLunches;
    'studentEthnicity'?: StudentEthnicity;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "blueRibbon",
            "baseName": "blueRibbon",
            "type": "string"
        },
        {
            "name": "internationalBaccalaureate",
            "baseName": "internationalBaccalaureate",
            "type": "string"
        },
        {
            "name": "titleI",
            "baseName": "titleI",
            "type": "string"
        },
        {
            "name": "expensePerStudent",
            "baseName": "expensePerStudent",
            "type": "string"
        },
        {
            "name": "studentBelowPovertyPct",
            "baseName": "studentBelowPovertyPct",
            "type": "string"
        },
        {
            "name": "advancePlacementClasses",
            "baseName": "advancePlacementClasses",
            "type": "string"
        },
        {
            "name": "freeOrReducedPriceLunches",
            "baseName": "freeOrReducedPriceLunches",
            "type": "FreeOrReducedPriceLunches"
        },
        {
            "name": "studentEthnicity",
            "baseName": "studentEthnicity",
            "type": "StudentEthnicity"
        }    ];

    static getAttributeTypeMap() {
        return SchoolProfile.attributeTypeMap;
    }
}

