/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SpecialPurposeDistrict {
    'districtName'?: string;
    'districtCode'?: string;
    'districtNumber'?: string;
    'versionDate'?: string;
    'effectiveDate'?: string;
    'compiledDate'?: string;
    'updateDate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "districtName",
            "baseName": "districtName",
            "type": "string"
        },
        {
            "name": "districtCode",
            "baseName": "districtCode",
            "type": "string"
        },
        {
            "name": "districtNumber",
            "baseName": "districtNumber",
            "type": "string"
        },
        {
            "name": "versionDate",
            "baseName": "versionDate",
            "type": "string"
        },
        {
            "name": "effectiveDate",
            "baseName": "effectiveDate",
            "type": "string"
        },
        {
            "name": "compiledDate",
            "baseName": "compiledDate",
            "type": "string"
        },
        {
            "name": "updateDate",
            "baseName": "updateDate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SpecialPurposeDistrict.attributeTypeMap;
    }
}

