/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 12.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Matrix } from './matrix';

export class TravelCostMatrixResponse {
    'matrix'?: Array<Matrix>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "matrix",
            "baseName": "matrix",
            "type": "Array<Matrix>"
        }    ];

    static getAttributeTypeMap() {
        return TravelCostMatrixResponse.attributeTypeMap;
    }
}

