/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetPostalCodesAPIOutputUserFields } from './getPostalCodesAPIOutputUserFields';

export class ValidateMailingAddressPremiumOutput {
    /**
    * These fields are returned, unmodified, in the user_fields section of the response.
    */
    'userFields'?: Array<GetPostalCodesAPIOutputUserFields>;
    /**
    * Reports the success or failure of the match attempt.
    */
    'status'?: string;
    /**
    * Reason for failure, if there is one.
    */
    'statusCode'?: string;
    /**
    * Description of the problem, if there is one.
    */
    'statusDescription'?: string;
    /**
    * The level of confidence assigned to the address being returned.
    */
    'confidence'?: string;
    /**
    * Type of address record.
    */
    'recordType'?: string;
    /**
    * Code indicating the default match.
    */
    'recordTypeDefault'?: string;
    /**
    * Indicates which address component had multiple matches.
    */
    'multipleMatches'?: string;
    /**
    * Mentions the address component that could not be validated, in case no match is found.
    */
    'couldNotValidate'?: string;
    /**
    * The category of address matching available.
    */
    'countryLevel'?: string;
    /**
    * The type of address data being returned.
    */
    'addressFormat'?: string;
    /**
    * The first line of the validated address.
    */
    'addressLine1'?: string;
    /**
    * The second line of the validated address.
    */
    'addressLine2'?: string;
    /**
    * The third line of the validated address.
    */
    'addressLine3'?: string;
    /**
    * The fourth line of the validated address.
    */
    'addressLine4'?: string;
    /**
    * The validated city name.
    */
    'city'?: string;
    /**
    * The validated state or province abbreviation.
    */
    'stateProvince'?: string;
    /**
    * The validated ZIP Code or postal code.
    */
    'postalCode'?: string;
    /**
    * The 5-digit ZIP Code.
    */
    'postalCodeBase'?: string;
    /**
    * The 4-digit add-on part of the ZIP Code.
    */
    'postalCodeAddOn'?: string;
    /**
    * The country in the format determined by what you selected.
    */
    'country'?: string;
    /**
    * Input data that could not be matched to a particular address component.
    */
    'additionalInputData'?: string;
    /**
    * The validated firm or company name.
    */
    'firmName'?: string;
    /**
    * House number.
    */
    'houseNumber'?: string;
    /**
    * Leading directional.
    */
    'leadingDirectional'?: string;
    /**
    * Street name.
    */
    'streetName'?: string;
    /**
    * Street suffix.
    */
    'streetSuffix'?: string;
    /**
    * Trailing directional.
    */
    'trailingDirectional'?: string;
    /**
    * Apartment designator (such as STE or APT).
    */
    'apartmentLabel'?: string;
    /**
    * Apartment number.
    */
    'apartmentNumber'?: string;
    /**
    * Secondary apartment designator.
    */
    'apartmentLabel2'?: string;
    /**
    * Secondary apartment number.
    */
    'apartmentNumber2'?: string;
    /**
    * Rural Route/Highway Contract indicator.
    */
    'rRHC'?: string;
    /**
    * Post office box number.
    */
    'pOBox'?: string;
    /**
    * Private mailbox indicator.
    */
    'privateMailbox'?: string;
    /**
    * The type of private mailbox.
    */
    'privateMailboxType'?: string;
    /**
    * House number.
    */
    'houseNumberInput'?: string;
    /**
    * Leading directional.
    */
    'leadingDirectionalInput'?: string;
    /**
    * Street name.
    */
    'streetNameInput'?: string;
    /**
    * Street suffix.
    */
    'streetSuffixInput'?: string;
    /**
    * Trailing directional.
    */
    'trailingDirectionalInput'?: string;
    /**
    * Apartment designator (such as STE or APT).
    */
    'apartmentLabelInput'?: string;
    /**
    * Apartment number.
    */
    'apartmentNumberInput'?: string;
    /**
    * Rural Route/Highway Contract indicator.
    */
    'rRHCInput'?: string;
    /**
    * Post office box number.
    */
    'pOBoxInput'?: string;
    /**
    * Private mailbox indicator.
    */
    'privateMailboxInput'?: string;
    /**
    * The type of private mailbox.
    */
    'privateMailboxTypeInput'?: string;
    /**
    * Validated city name.
    */
    'cityInput'?: string;
    /**
    * Validated state or province name.
    */
    'stateProvinceInput'?: string;
    /**
    * Validated postal code.
    */
    'postalCodeInput'?: string;
    /**
    * Country. Format is determined by what you selected in OutputCountryFormat.
    */
    'countryInput'?: string;
    /**
    * The validated firm or company name.
    */
    'firmNameInput'?: string;
    /**
    * The field-level result indicator for HouseNumber.
    */
    'houseNumberResult'?: string;
    /**
    * The field-level result indicator for LeadingDirectional.
    */
    'leadingDirectionalResult'?: string;
    /**
    * The field-level result indicator for Street.
    */
    'streetResult'?: string;
    /**
    * The field-level result indicator for StreetName.
    */
    'streetNameResult'?: string;
    /**
    * The field-level result indicator for StreetName Alias.
    */
    'streetNameAliasType'?: string;
    /**
    * The field-level result indicator for StreetSuffix.
    */
    'streetSuffixResult'?: string;
    /**
    * The field-level result indicator for TrailingDirectional.
    */
    'trailingDirectionalResult'?: string;
    /**
    * The field-level result indicator for ApartmentLabel.
    */
    'apartmentLabelResult'?: string;
    /**
    * The field-level result indicator for ApartmentNumber.
    */
    'apartmentNumberResult'?: string;
    /**
    * The field-level result indicator for ApartmentLabel2.
    */
    'apartmentLabel2Result'?: string;
    /**
    * The field-level result indicator for ApartmentNumber2.
    */
    'apartmentNumber2Result'?: string;
    /**
    * The field-level result indicator for RRHC.
    */
    'rRHCResult'?: string;
    /**
    * The field-level result indicator for RRHC Type.
    */
    'rRHCType'?: string;
    /**
    * The field-level result indicator for POBox.
    */
    'pOBoxResult'?: string;
    /**
    * The field-level result indicator for City.
    */
    'cityResult'?: string;
    /**
    * The field-level result indicator for StateProvince.
    */
    'stateProvinceResult'?: string;
    /**
    * The field-level result indicator for PostalCode.
    */
    'postalCodeResult'?: string;
    /**
    * The field-level result indicator for PostalCodeCity.
    */
    'postalCodeCityResult'?: string;
    /**
    * The field-level result indicator for AddressRecord.
    */
    'addressRecordResult'?: string;
    /**
    * The field-level result indicator for PostalCode Source.
    */
    'postalCodeSource'?: string;
    /**
    * Indicates the type of postal code returned.
    */
    'postalCodeType'?: string;
    /**
    * The validated firm or company name.
    */
    'countryResult'?: string;
    /**
    * Indicates if the firm name got validated.
    */
    'firmNameResult'?: string;
    /**
    * Indicates the result of preferred alias processing.
    */
    'streetNamePreferredAliasResult'?: string;
    /**
    * Indicates the result of abbreviated alias processing.
    */
    'streetNameAbbreviatedAliasResult'?: string;
    /**
    * The fifth line of the validated address.
    */
    'addressLine5'?: string;
    /**
    * A two character code indicating overall quality of the resulting address.
    */
    'addressQuality'?: string;
    /**
    * An estimate of confidence that an item mailed or shipped to this address would be successfully delivered.
    */
    'deliverability'?: string;
    /**
    * A single letter code that indicates the type of address.
    */
    'addressType'?: string;
    /**
    * A locality is a village in rural areas or it may be a suburb in urban areas.
    */
    'locality'?: string;
    /**
    * A value of 0 and 100 that reflects how much the address has changed to make it valid.
    */
    'changeScore'?: string;
    /**
    * The validated firm or company name.
    */
    'suburb'?: string;
    /**
    * It is the formatted address, as it would appear on a physical mail piece.
    */
    'blockAddress'?: string;
    /**
    * Seven-digit number in degrees, calculated to four decimal places.
    */
    'latitude'?: string;
    /**
    * Seven-digit number in degrees, calculated to four decimal places.
    */
    'longitude'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "userFields",
            "baseName": "user_fields",
            "type": "Array<GetPostalCodesAPIOutputUserFields>"
        },
        {
            "name": "status",
            "baseName": "Status",
            "type": "string"
        },
        {
            "name": "statusCode",
            "baseName": "Status.Code",
            "type": "string"
        },
        {
            "name": "statusDescription",
            "baseName": "Status.Description",
            "type": "string"
        },
        {
            "name": "confidence",
            "baseName": "Confidence",
            "type": "string"
        },
        {
            "name": "recordType",
            "baseName": "RecordType",
            "type": "string"
        },
        {
            "name": "recordTypeDefault",
            "baseName": "RecordType.Default",
            "type": "string"
        },
        {
            "name": "multipleMatches",
            "baseName": "MultipleMatches",
            "type": "string"
        },
        {
            "name": "couldNotValidate",
            "baseName": "CouldNotValidate",
            "type": "string"
        },
        {
            "name": "countryLevel",
            "baseName": "CountryLevel",
            "type": "string"
        },
        {
            "name": "addressFormat",
            "baseName": "AddressFormat",
            "type": "string"
        },
        {
            "name": "addressLine1",
            "baseName": "AddressLine1",
            "type": "string"
        },
        {
            "name": "addressLine2",
            "baseName": "AddressLine2",
            "type": "string"
        },
        {
            "name": "addressLine3",
            "baseName": "AddressLine3",
            "type": "string"
        },
        {
            "name": "addressLine4",
            "baseName": "AddressLine4",
            "type": "string"
        },
        {
            "name": "city",
            "baseName": "City",
            "type": "string"
        },
        {
            "name": "stateProvince",
            "baseName": "StateProvince",
            "type": "string"
        },
        {
            "name": "postalCode",
            "baseName": "PostalCode",
            "type": "string"
        },
        {
            "name": "postalCodeBase",
            "baseName": "PostalCode.Base",
            "type": "string"
        },
        {
            "name": "postalCodeAddOn",
            "baseName": "PostalCode.AddOn",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "Country",
            "type": "string"
        },
        {
            "name": "additionalInputData",
            "baseName": "AdditionalInputData",
            "type": "string"
        },
        {
            "name": "firmName",
            "baseName": "FirmName",
            "type": "string"
        },
        {
            "name": "houseNumber",
            "baseName": "HouseNumber",
            "type": "string"
        },
        {
            "name": "leadingDirectional",
            "baseName": "LeadingDirectional",
            "type": "string"
        },
        {
            "name": "streetName",
            "baseName": "StreetName",
            "type": "string"
        },
        {
            "name": "streetSuffix",
            "baseName": "StreetSuffix",
            "type": "string"
        },
        {
            "name": "trailingDirectional",
            "baseName": "TrailingDirectional",
            "type": "string"
        },
        {
            "name": "apartmentLabel",
            "baseName": "ApartmentLabel",
            "type": "string"
        },
        {
            "name": "apartmentNumber",
            "baseName": "ApartmentNumber",
            "type": "string"
        },
        {
            "name": "apartmentLabel2",
            "baseName": "ApartmentLabel2",
            "type": "string"
        },
        {
            "name": "apartmentNumber2",
            "baseName": "ApartmentNumber2",
            "type": "string"
        },
        {
            "name": "rRHC",
            "baseName": "RRHC",
            "type": "string"
        },
        {
            "name": "pOBox",
            "baseName": "POBox",
            "type": "string"
        },
        {
            "name": "privateMailbox",
            "baseName": "PrivateMailbox",
            "type": "string"
        },
        {
            "name": "privateMailboxType",
            "baseName": "PrivateMailbox.Type",
            "type": "string"
        },
        {
            "name": "houseNumberInput",
            "baseName": "HouseNumber.Input",
            "type": "string"
        },
        {
            "name": "leadingDirectionalInput",
            "baseName": "LeadingDirectional.Input",
            "type": "string"
        },
        {
            "name": "streetNameInput",
            "baseName": "StreetName.Input",
            "type": "string"
        },
        {
            "name": "streetSuffixInput",
            "baseName": "StreetSuffix.Input",
            "type": "string"
        },
        {
            "name": "trailingDirectionalInput",
            "baseName": "TrailingDirectional.Input",
            "type": "string"
        },
        {
            "name": "apartmentLabelInput",
            "baseName": "ApartmentLabel.Input",
            "type": "string"
        },
        {
            "name": "apartmentNumberInput",
            "baseName": "ApartmentNumber.Input",
            "type": "string"
        },
        {
            "name": "rRHCInput",
            "baseName": "RRHC.Input",
            "type": "string"
        },
        {
            "name": "pOBoxInput",
            "baseName": "POBox.Input",
            "type": "string"
        },
        {
            "name": "privateMailboxInput",
            "baseName": "PrivateMailbox.Input",
            "type": "string"
        },
        {
            "name": "privateMailboxTypeInput",
            "baseName": "PrivateMailbox.Type.Input",
            "type": "string"
        },
        {
            "name": "cityInput",
            "baseName": "City.Input",
            "type": "string"
        },
        {
            "name": "stateProvinceInput",
            "baseName": "StateProvince.Input",
            "type": "string"
        },
        {
            "name": "postalCodeInput",
            "baseName": "PostalCode.Input",
            "type": "string"
        },
        {
            "name": "countryInput",
            "baseName": "Country.Input",
            "type": "string"
        },
        {
            "name": "firmNameInput",
            "baseName": "FirmName.Input",
            "type": "string"
        },
        {
            "name": "houseNumberResult",
            "baseName": "HouseNumber.Result",
            "type": "string"
        },
        {
            "name": "leadingDirectionalResult",
            "baseName": "LeadingDirectional.Result",
            "type": "string"
        },
        {
            "name": "streetResult",
            "baseName": "Street.Result",
            "type": "string"
        },
        {
            "name": "streetNameResult",
            "baseName": "StreetName.Result",
            "type": "string"
        },
        {
            "name": "streetNameAliasType",
            "baseName": "StreetName.Alias.Type",
            "type": "string"
        },
        {
            "name": "streetSuffixResult",
            "baseName": "StreetSuffix.Result",
            "type": "string"
        },
        {
            "name": "trailingDirectionalResult",
            "baseName": "TrailingDirectional.Result",
            "type": "string"
        },
        {
            "name": "apartmentLabelResult",
            "baseName": "ApartmentLabel.Result",
            "type": "string"
        },
        {
            "name": "apartmentNumberResult",
            "baseName": "ApartmentNumber.Result",
            "type": "string"
        },
        {
            "name": "apartmentLabel2Result",
            "baseName": "ApartmentLabel2.Result",
            "type": "string"
        },
        {
            "name": "apartmentNumber2Result",
            "baseName": "ApartmentNumber2.Result",
            "type": "string"
        },
        {
            "name": "rRHCResult",
            "baseName": "RRHC.Result",
            "type": "string"
        },
        {
            "name": "rRHCType",
            "baseName": "RRHC.Type",
            "type": "string"
        },
        {
            "name": "pOBoxResult",
            "baseName": "POBox.Result",
            "type": "string"
        },
        {
            "name": "cityResult",
            "baseName": "City.Result",
            "type": "string"
        },
        {
            "name": "stateProvinceResult",
            "baseName": "StateProvince.Result",
            "type": "string"
        },
        {
            "name": "postalCodeResult",
            "baseName": "PostalCode.Result",
            "type": "string"
        },
        {
            "name": "postalCodeCityResult",
            "baseName": "PostalCodeCity.Result",
            "type": "string"
        },
        {
            "name": "addressRecordResult",
            "baseName": "AddressRecord.Result",
            "type": "string"
        },
        {
            "name": "postalCodeSource",
            "baseName": "PostalCode.Source",
            "type": "string"
        },
        {
            "name": "postalCodeType",
            "baseName": "PostalCode.Type",
            "type": "string"
        },
        {
            "name": "countryResult",
            "baseName": "Country.Result",
            "type": "string"
        },
        {
            "name": "firmNameResult",
            "baseName": "FirmName.Result",
            "type": "string"
        },
        {
            "name": "streetNamePreferredAliasResult",
            "baseName": "StreetNamePreferredAlias.Result",
            "type": "string"
        },
        {
            "name": "streetNameAbbreviatedAliasResult",
            "baseName": "StreetNameAbbreviatedAlias.Result",
            "type": "string"
        },
        {
            "name": "addressLine5",
            "baseName": "AddressLine5",
            "type": "string"
        },
        {
            "name": "addressQuality",
            "baseName": "AddressQuality",
            "type": "string"
        },
        {
            "name": "deliverability",
            "baseName": "Deliverability",
            "type": "string"
        },
        {
            "name": "addressType",
            "baseName": "AddressType",
            "type": "string"
        },
        {
            "name": "locality",
            "baseName": "Locality",
            "type": "string"
        },
        {
            "name": "changeScore",
            "baseName": "ChangeScore",
            "type": "string"
        },
        {
            "name": "suburb",
            "baseName": "Suburb",
            "type": "string"
        },
        {
            "name": "blockAddress",
            "baseName": "BlockAddress",
            "type": "string"
        },
        {
            "name": "latitude",
            "baseName": "Latitude",
            "type": "string"
        },
        {
            "name": "longitude",
            "baseName": "Longitude",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ValidateMailingAddressPremiumOutput.attributeTypeMap;
    }
}

