/**
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ValidateEmailAddressInput } from './validateEmailAddressInput';

export class ValidateEmailAddressAPIRequest {
    'options'?: object;
    'input'?: ValidateEmailAddressInput;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "options",
            "baseName": "options",
            "type": "object"
        },
        {
            "name": "input",
            "baseName": "Input",
            "type": "ValidateEmailAddressInput"
        }    ];

    static getAttributeTypeMap() {
        return ValidateEmailAddressAPIRequest.attributeTypeMap;
    }
}

